version: '3'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      db:
        condition: service_healthy
    environment:
      - DB_CONNECTION_STRING=postgres://user:password@db/filedb?sslmode=disable
    networks:
      - mynetwork

  db:
    image: postgres:13
    environment:
      POSTGRES_DB: filedb
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    networks:
      - mynetwork
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d filedb"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

networks:
  mynetwork:

volumes:
  pgdata: